### ISSUE TITLE
BaseTest().newWaitWithTimeout(timeout).until(Expected.Conditions....) no longer works with frameworkum 2.4.2

### ISSUE THREAD

**Issue by Mjl33** [Frameworkium/frameworkium-core#72]
This is attributed to Selenium 3.4.0 vs Selenium 3.0.1 

results in compilation error
```
 method until in interface org.openqa.selenium.support.ui.Wait<F> cannot be applied to given types;
[ERROR] required: java.util.function.Function<? super org.openqa.selenium.WebDriver,T>
[ERROR] found: org.openqa.selenium.support.ui.ExpectedCondition<java.lang.Boolean>
[ERROR] reason: cannot infer type-variable(s) T
[ERROR] (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<java.lang.Boolean> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,T>)
```

When Frameworkium 2.4.2 is forced to downgrade to Selenium 3.0.1, it will compile

**Comment by Hyphen31** [comment]
This is a Guava issue. My latest pull request [#70](https://github.com/Frameworkium/frameworkium-core/pull/70) adds an explicit Guava v23 dependency into the pom which addresses this.

**Comment by ham1** [comment]
Is this now fixed in v2.4.3?

**Comment by Hyphen31** [comment]
It should be.

**Comment by noronhaa** [comment]
It seems not, I had to add an explicit guava 23.0 dependency in my child project to fix the issue when using Frameworkium-core 2.4.3. Would be good to see if it is the same for anyone else

**Comment by ham1** [comment]
Long shot but did you clear your .m2 dir to make sure there's nothing conflicting in there?

**Comment by noronhaa** [comment]
I have got it to work now, I had to exclude guava from several other dependencies I had in my pom, I guess explicitly declaring a guava 23 dependency was overriding all of them, if I didn't do this, is was using guava from my other dependencies over frameworkiums explicit guava dependency
